config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :topics
  resources :replies
  resources :users, only: :index, param: :username do
    get :topics, on: :member
    get :replies, on: :member
    get :favorites, on: :member
  end
  resource :profile, only: [:edit, :update, :create]
  resources :notifications, only: [:index, :destroy]
  resources :favorites, only: [:create, :destroy] do
    delete :destroy, on: :collection
  end
  resource :avatar, only: :update

  get  'qiniu_uptoken', to: 'qiniu_uptoken#show'
  post 'markdown_preview', to: 'markdown_preview#show'
  get  'search', to: 'search#show'

  get ':username', to: 'users#show', username: /\w+/, as: :user

  root 'topics#index'
end

app/models/notification/base.rb
module Notification
  class Base < ActiveRecord::Base
    self.table_name = 'notifications'

    belongs_to :user, counter_cache: :notifications_count

    after_create :increase_user_unread_notifications_count_after_create
    after_destroy :decrease_user_unread_notifications_count_after_destroy
    after_update :update_user_unread_notifications_count_after_update

    def read?
      read
    end

    def unread?
      !read?
    end

    def unread!
      update_attributes(read: false)
    end

    def read!
      update_attributes(read: true)
    end

    private

    def increase_user_unread_notifications_count_after_create
      user.increment!(:unread_notifications_count)
    end

    def decrease_user_unread_notifications_count_after_destroy
      user.decrement!(:unread_notifications_count) if unread?
    end

    def update_user_unread_notifications_count_after_update
      if read_changed? && read?
        user.decrement!(:unread_notifications_count)
      elsif read_changed? && unread?
        user.increment!(:unread_notifications_count)
      end
    end
  end
end

app/models/notification/favorite.rb
module Notification
  class Favorite < Base
    belongs_to :favorite, class_name: '::Favorite'
  end
end

app/models/notification/favorited_reply.rb
module Notification
  class FavoritedReply < Base
    belongs_to :reply, class_name: '::Reply'
  end
end

app/models/notification/mention.rb
module Notification
  class Mention < Base
    belongs_to :mention, class_name: '::Mention'
  end
end

app/models/notification/reply.rb
module Notification
  class Reply < Base
    belongs_to :reply, class_name: '::Reply'
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.
      notifications.
      order(read: :asc, id: :desc).
      paginate(page: params[:page])

    read_notifications(@notifications)
  end

  def destroy
    notification = Notification::Base.find_by_id(params[:id])

    if notification
      notification.destroy

      head :no_content
    else
      head :not_found
    end
  end

  private

  def read_notifications(notifications)
    unread_notifications = notifications.select(&:unread?)

    notifications.select(&:unread?).each do |unread_notification|
      unread_notification.read!
      unread_notification.read = false
    end
  end
end

app/views/notifications/item/_favorite.html.slim
- if favorite.favoritable
  - case favorite.favoritable
  - when Topic
    .favorite
      .avatar
        = link_to user_path(favorite.favoritable.user_name) do
          = image_tag favorite.favoritable.user_avatar
      .info
        = render partial: 'notifications/item/favorite/topic',
                 locals: { notification: notification,
                           favorite: favorite,
                           topic: favorite.favoritable }
  - when Reply
    - if favorite.favoritable.topic
      .favorite
        .avatar
          = link_to user_path(favorite.favoritable.user_name) do
            = image_tag favorite.favoritable.user_avatar

        .info
          = render partial: 'notifications/item/favorite/reply',
                   locals: { notification: notification,
                             favorite: favorite,
                             reply: favorite.favoritable }
    - else
      .content-deleted
        = t('notification.content_already_deleted')
        '
        = link_to '', '#', data: { id: notification.id }, class: 'fa fa-close'
- else
  .content-deleted
    = t('notification.content_already_deleted')
    '
    = link_to '', '#', data: { id: notification.id }, class: 'fa fa-close'

app/views/notifications/item/_favorited_reply.html.slim
- if reply.topic
  .favorited-reply
    .avatar
      = link_to user_path(reply.user_name) do
        = image_tag reply.user_avatar
    .info
      .notification-title
        = sanitize(t('notification.favorited_reply_link',
                      user: link_to(reply.user_name, user_path(reply.user_name)),
                      topic: link_to(reply.topic.title, topic_path(reply.topic))),
                   tags: %w(a))
      .tips
        = reply_link(reply)
        '  &middot;
        = timeago_tag(notification.created_at)
    .body
      = sanitize_body_html(reply.body_html)
- else
  .content-deleted
    = t('notification.content_already_deleted')
    '
    = link_to '', '#', data: { id: notification.id }, class: 'fa fa-close'

app/views/notifications/item/_mention.html.slim
- if mention.mentionable
  - case mention.mentionable
  - when Topic
    .mention
      .avatar
        = link_to user_path(mention.mentionable) do
          = image_tag mention.mentionable.user_avatar
      .info
        = render partial: 'notifications/item/mention/topic',
                   locals: { notification: notification,
                             topic: mention.mentionable }
      .body
        = sanitize_body_html(mention.mentionable.body_html)
  - when Reply
    - if mention.mentionable.topic
      .mention
        .avatar
          = link_to user_path(mention.mentionable) do
            = image_tag mention.mentionable.user_avatar
        .info
          = render partial: 'notifications/item/mention/reply',
               locals: { notification: notification,
                         reply: mention.mentionable }

        .body
          = sanitize_body_html(mention.mentionable.body_html)
    - else
      .content-deleted
        = t('notification.content_already_deleted')
        '
        = link_to '', '#', data: { id: notification.id }, class: 'fa fa-close'
- else
  .content-deleted
    = t('notification.content_already_deleted')
    '
    = link_to '', '#', data: { id: notification.id }, class: 'fa fa-close'

app/views/notifications/item/_reply.html.slim
- if reply.topic
  .reply
    .avatar
      = link_to user_path(reply.user_name) do
        = image_tag reply.user_avatar
    .info
      .notification-title
        = sanitize(t('notification.reply_link',
                      user: link_to(reply.user_name, user_path(reply.user_name)),
                      topic: link_to(reply.topic.title, topic_path(reply.topic))),
                   tags: %w(a))
      .tips
        = reply_link(reply)
        '  &middot;
        = timeago_tag(notification.created_at)
    .body
      = sanitize_body_html(reply.body_html)
- else
  .content-deleted
    =t('notification.content_already_deleted')
    '
    = link_to '', '#', data: { id: notification.id }, class: 'fa fa-close'