config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :topics
  resources :replies
  resources :users, only: :index, param: :username do
    get :topics, on: :member
    get :replies, on: :member
    get :favorites, on: :member
  end
  resource :profile, only: [:edit, :update, :create]
  resources :notifications, only: [:index, :destroy]
  resources :favorites, only: [:create, :destroy] do
    delete :destroy, on: :collection
  end
  resource :avatar, only: :update

  get  'qiniu_uptoken', to: 'qiniu_uptoken#show'
  post 'markdown_preview', to: 'markdown_preview#show'
  get  'search', to: 'search#show'

  get ':username', to: 'users#show', username: /\w+/, as: :user

  root 'topics#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Markdownable
  include Mentionable
  include Favoritable

  acts_as_paranoid

  belongs_to :user, counter_cache: true
  belongs_to :node, counter_cache: true
  has_many :replies
  has_many :favorites, as: :favoritable
  has_many :mentions, as: :mentionable

  validates :user_id, presence: true
  validates :user_name, presence: true
  validates :user_avatar, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :actived_at, presence: true
  validates :node_id, presence: true

  before_validation :set_attributes_before_validation, on: :create
  before_validation :set_node_name_before_validation
  after_create :update_user_read_topic_after_create

  def stick?
    stick
  end

  def stick!
    update_attributes(stick: true)
  end

  def unstick!
    update_attributes(stick: false)
  end

  def has_replies?
    !replies_count.zero?
  end

  def has_favorites?
    !favorites_count.zero?
  end

  def node_others(count=5)
    others(count, node_id: node_id)
  end

  def user_others(count=5)
    others(count, user_id: user_id)
  end

  private

  def others(count, query)
    self.class.
      where(query).
      where('id != ?', id).
      order(id: :desc).
      first(count)
  end

  def set_attributes_before_validation
    assign_attributes(
      user_name: user.name,
      user_avatar: user.avatar,
      actived_at: Time.now
    )
  end

  def set_node_name_before_validation
    self.node_name = node.name if node_id_changed?
  end

  def update_user_read_topic_after_create
    user.update_read_topic(self)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action { @topbar = :community }

  def index
    @topics = Topic.without_body.order(stick: :desc, actived_at: :desc)

    if params[:node]
      @node = Node.find_by_name(params[:node])

      @topics = @topics.where(node_id: @node.id)
    end

    @topics = @topics.paginate(page: params[:page])
  end

  def new
    node = Node.find_by_name(params[:node]) if params[:node]

    @topic = Topic.new(node: node)
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      flash[:success] = t('topic.created_success')

      redirect_to topics_path
    else
      flash.now[:alert] = @topic.errors.full_messages.join(', ')

      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])

    current_user.update_read_topic(@topic) if current_user

    @replies = @topic.replies.with_deleted.order(:floor).paginate(page: params[:page])
  end

  def edit
    @topic = current_user.topics.find(params[:id])
  end

  def update
    @topic = current_user.topics.find(params[:id])

    if @topic.update_attributes(topic_params)
      flash[:success] = t('topic.updated_success')

      redirect_to topic_path(@topic)
    else
      flash.now[:alert] = @topic.errors.full_messages.join(', ')

      render :edit
    end
  end

  def destroy
    if topic = current_user.topics.find(params[:id])
      topic.destroy

      flash[:success] = t('topic.deleted_success')

      redirect_to topics_path
    else
      head :not_found
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body, :node_id)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def replies_count_link(topic)
    options = {}

    if topic.has_replies?
      page = Reply.page_of_floor(topic.replies_count)

      options.merge!(page: page, anchor: "reply-#{topic.replies_count}")
    end

    klass = signed_in? && current_user.has_read_topic?(topic) ? 'label secondary' : 'label'

    link_to topic.replies_count, topic_path(topic, options), class: klass
  end

  def reply_link(reply)
    page = Reply.page_of_floor(reply.floor)

    text = "##{reply.floor}#{t('activerecord.attributes.reply.floor')}"
    anchor = "reply-#{reply.floor}"

    link_to text, topic_path(reply.topic, page: page, anchor: anchor)
  end

  def favorite_link(favoritable)
    favorite_klass =
      (signed_in? && favoritable.favorited_by?(current_user)) ?
        'fa fa-heart favorited' : 'fa fa-heart-o unfavorited'

    link_to '#', class: favorite_klass,
                 data: { favoritable_id: favoritable.id,
                         favoritable_type: favoritable.class.name } do
      content_tag :span, favoritable.favorites_count, class: 'count'
    end
  end
end

app/views/topics/_form.html.slim
.topic-form
  = form_for topic do |f|
    = f.select :node_id, Node.all.map { |n| [n.name, n.id] }, prompt: t('topic.choose_a_node')
    = f.text_field :title, placeholder: t('topic.title')
    .tools
      .clearfix
        = link_to '', '#', class: 'fa fa-eye left preview'
        - if signed_in?
          = link_to '', '#',
            class: 'fa fa-image right',
            id: 'upload',
            data: { qiniu_domain: Rails.application.secrets.qiniu_domain,
                    topic_id: topic.id }
    = f.text_area :body, placeholder: t('topic.body'), size: 'x20'
    .clearfix
      = f.submit t('submit'), class: 'button small right', data: { disable_with: t('submiting') }

app/views/topics/_item.html.slim
.item
  .user-avatar
    = link_to user_path(topic.user_name) do
      = image_tag topic.user_avatar
  .info
    = link_to topic.title.truncate(50), topic_path(topic), class: 'title'
    .lightsmall
      .show-for-small-only
        - if topic.has_replies?
          span
            = link_to topic.last_replied_user_name, user_path(topic.last_replied_user_name)
            '
            = timeago_tag topic.last_replied_at
            ' 回复
        - else
          span
            = link_to topic.user_name, user_path(topic.user_name)
            '
            = timeago_tag topic.created_at
            ' 发布
        - if topic.has_favorites?
          ' &middot;
          span
            i.fa.fa-heart
              '
              = topic.favorites_count

      .show-for-medium-up
        span
          = link_to topic.user_name, user_path(topic.user_name)
          '
        - unless topic.has_replies?
          '
          = timeago_tag topic.created_at
          ' 发布
        - else
          ' &middot;
          span
            = link_to topic.last_replied_user_name, user_path(topic.last_replied_user_name)
            '
            = timeago_tag topic.last_replied_at
            ' 回复
        - if topic.has_favorites?
          ' &middot;
          span
            i.fa.fa-heart
              '
              = topic.favorites_count

  .replies-count
    = last_reply_link(topic)

app/views/topics/_replies.html.slim
.replies
  - replies.each do |reply|
    = render partial: 'reply_item', locals: { reply: reply }

.clearfix
  = will_paginate(replies, renderer: FoundationPagination::Rails)

app/views/topics/_reply_item.html.slim
.item id="reply-#{reply.floor}"
  - if reply.deleted?
    center.deleted
      p
        i
          s #{reply.floor} 楼已删除
  - else
    .user-avatar
      = link_to user_path(reply.user_name) do
        = image_tag reply.user_avatar

    .info
      .lightsmall
        span = reply.floor
        ' 楼
        ' &middot;
        span
          = link_to reply.user_name, user_path(reply.user_name)
          '
          = timeago_tag reply.created_at
        - if signed_in?
          span.reply.right
            = link_to '#', data: { reply_floor: reply.floor, reply_user_name: reply.user_name } do
              i.fa.fa-reply

    .body.markdown
      = raw sanitize_body_html(reply.body_html)

    .clearfix
      .lightsmall
        - if signed_in? && current_user.id.eql?(reply.user_id)
          span.right
            = link_to reply_path(reply), method: :delete, remote: true, data: { confirm: '确定删除该回复?' } do
              i.fa.fa-trash
          span.right &nbsp;
          span.right
            = link_to edit_reply_path(reply) do
              i.fa.fa-pencil

app/views/topics/_topic.html.slim
.topic
  .user-avatar
    = link_to user_path(topic.user_name) do
      = image_tag topic.user_avatar
  .info
    = link_to topic.title, topic_path(topic), class: 'title'
    .lightsmall
      .show-for-small-only
        span
          = link_to topic.user_name, user_path(topic.user_name)
          '
          = timeago_tag topic.created_at
          ' 发布
      .show-for-medium-up
        span
          = link_to topic.user_name, user_path(topic.user_name)
          '
          = timeago_tag topic.created_at
          ' 发布
        - if topic.has_replies?
          ' &middot;
          span
            = link_to topic.last_replied_user_name, user_path(topic.last_replied_user_name)
            '
            = timeago_tag topic.last_replied_at
            ' 回复
  .favorite
    span
      - if signed_in? && current_user.favorited?(topic)
        = link_to favorites_path(favoritable_id: topic.id, favoritable_type: topic.class.to_s), class: :favorited, method: :delete, remote: true do
          i.fa.fa-heart
            span.count = topic.favorites_count
      - else
        = link_to favorites_path(favoritable_id: topic.id, favoritable_type: topic.class.to_s), class: :unfavorited, method: :post, remote: true do
          i.fa.fa-heart-o
            span.count = topic.favorites_count

  .body.markdown
    = raw sanitize_body_html(topic.body_html)

  .clearfix
    .lightsmall
      - if signed_in? && current_user.id.eql?(topic.user_id)
        span.right
          = link_to topic_path(topic), method: :delete, data: { confirm: '确定删除该贴?' } do
            i.fa.fa-trash
        span.right &nbsp;
        span.right
          = link_to edit_topic_path(topic) do
            i.fa.fa-pencil

app/views/topics/edit.html.slim
.row.small-collapse.medium-uncollapse.large-uncollapse
  .large-8.columns
    .box
      = render partial: 'form', locals: { topic: @topic }
  .show-for-large-up.large-4.columns.no-padding-left
    = render partial: 'common/markdown_tips'

app/views/topics/index.html.slim
.row.small-collapse.medium-uncollapse
  .large-8.columns
    .box
      .clearfix
        = link_to t('topic.new_button'), new_topic_path(node: @node.try(:name)), { class: 'button small right' }
      .topics
        - @topics.each do |topic|
          = render partial: 'topics/index/item', locals: { topic: topic }
      .clearfix
        = will_paginate(@topics, renderer: FoundationPagination::Rails)
  .show-for-medium-up.large-4.columns.no-padding-left-large-up
    = render partial: 'topics/index/side', locales: { node: @node }

app/views/topics/new.html.slim
.row.small-collapse.medium-uncollapse
  .large-8.columns
    .box
      = render partial: 'form', locals: { topic: @topic }
  .show-for-large-up.large-4.columns.no-padding-left
    = render partial: 'common/markdown_tips'

app/views/topics/show.html.slim
.row.small-collapse.medium-uncollapse
  .large-8.columns
    .box
      = render partial: 'topics/show/topic', locals: { topic: @topic }
    - if @topic.has_replies?
      .box
        = render partial: 'topics/show/replies', locals: { replies: @replies }
    .box
      = render partial: 'replies/form', locals: { topic: @topic, reply: @topic.replies.new }

  .show-for-medium-up.large-4.columns.no-padding-left-large-up
    = render partial: 'topics/show/side', locals: { topic: @topic }