config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :topics
  resources :replies
  resources :users, only: :index, param: :username do
    get :topics, on: :member
    get :replies, on: :member
    get :favorites, on: :member
  end
  resource :profile, only: [:edit, :update, :create]
  resources :notifications, only: [:index, :destroy]
  resources :favorites, only: [:create, :destroy] do
    delete :destroy, on: :collection
  end
  resource :avatar, only: :update

  get  'qiniu_uptoken', to: 'qiniu_uptoken#show'
  post 'markdown_preview', to: 'markdown_preview#show'
  get  'search', to: 'search#show'

  get ':username', to: 'users#show', username: /\w+/, as: :user

  root 'topics#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  DEFAULT_AVATAR = '/images/avatar.png'

  include TopicReadable

  attr_accessor :login

  devise :database_authenticatable,
         :registerable,
         :omniauthable,
         :validatable,
         :recoverable,
         :confirmable,
         :trackable,
         :rememberable,
         authentication_keys: [:login],
         omniauth_providers: [:github, :twitter]

  has_one :authorization
  has_one :profile
  has_many :topics
  has_many :replies
  has_many :favorites
  has_many :mentions
  has_many :notifications, class_name: 'Notification::Base'

  validates :name,
    uniqueness: { case_sensitive: false },
    length: { in: 3..20 },
    format: { with: /\A\w+\Z/ }

  before_save :set_default_avatar_before_save, unless: :has_avatar?
  after_update :set_topics_and_replies_user_avatar_after_update, if: :avatar_changed?
  after_update :notify_unread_notifications_count_after_update, if: :unread_notifications_count_changed?

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup

    login = conditions.delete(:login)

    where(conditions).
      where('lower(name) = :value OR lower(email) = :value',
            { value: login.downcase }).
      first
  end

  def update_with_password(params, *options)
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = if encrypted_password
               if valid_password?(current_password)
                 update_attributes(params, *options)
               else
                 assign_attributes(params, *options)
                 valid?
                 errors.add(:current_password, current_password.blank? ? :blank : :invalid)
                 false
               end
             else
               update_attributes(params, *options)
             end

    clean_up_passwords

    result
  end

  def has_unread_notifications?
    unread_notifications_count > 0
  end

  def has_avatar?
    avatar.present?
  end

  def password_required?
    authorization.blank? && super
  end

  def email_required?
    authorization.blank? && super
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  private

  def set_default_avatar_before_save
    self.avatar = DEFAULT_AVATAR if avatar.blank?
  end

  def set_topics_and_replies_user_avatar_after_update
    topics.update_all(user_avatar: avatar)
    replies.update_all(user_avatar: avatar)
  end

  def notify_unread_notifications_count_after_update
    ActionCableJobs::NotifyUnreadNotificationsCount.perform_later(id, unread_notifications_count)
  end
end

app/controllers/users/confirmations_controller.rb
module Users
  class ConfirmationsController < Devise::ConfirmationsController
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      execute(request.env['omniauth.auth'])
    end

    def twitter
      execute(request.env['omniauth.auth'])
    end

    private

    def execute(auth)
      provider = auth.provider
      uid      = auth.uid
      name     = auth.info.nickname
      email    = auth.info.email
      avatar   = auth.info.image

      if authorization = Authorization.find_by_provider_and_uid(provider, uid)
        user = authorization.user
      else
        user = User.new(
          name: name,
          email: email,
          avatar: avatar)

        user.skip_confirmation!

        user.build_authorization(provider: provider, uid: uid)

        unless user.save
          flash[:alert] = user.errors.full_messages.join(', ')

          return(redirect_to new_user_session_path)
        end
      end

      set_flash_message(:notice, :success, kind: provider.capitalize)
      sign_in_and_redirect user
    end
  end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

    private

    def configure_permitted_parameters
      sign_up_permited_params = %i(name email password password_confirmation)

      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(*sign_up_permited_params) }
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    respond_to :html, :js
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action { @topbar = :user }
  before_action :user, except: :index

  def show
    topics
  end

  def topics
    @topics = user.
      topics.
      without_body.
      order(id: :desc).
      paginate(page: params[:page])

    render :show
  end

  def replies
    @replies = user.
      replies.
      includes(:topic).
      order(id: :desc).
      paginate(page: params[:page])

    render :show
  end

  def favorites
    @favorites = user.favorites.order(id: :desc).paginate(page: params[:page])

    render :show
  end

  def index
    @users = User.order(id: :asc).paginate(page: params[:page], per_page: 50)
  end

  private

  def user
    @user ||= (params[:username].present? &&
               User.where('lower(name) = ?', params[:username].downcase).first) ||
                  (raise ActionController::RoutingError.new('Routing Error'))
  end
end

app/views/users/_activity.html.slim
.activity
  ul.tabs
    li.tab-title class=(:active if topics)
      = link_to t('user.latest_topics'), topics_user_path(@user.name)
    li.tab-title class=(:active if replies)
      = link_to t('user.latest_replies'), replies_user_path(@user.name)
    li.tab-title class=(:active if favorites)
      = link_to t('user.latest_favorites'), favorites_user_path(@user.name)
  .tabs-content
    - if topics
      #topics.content.active
        = render partial: 'users/activity/topics', locals: { topics: topics }
      = will_paginate(topics, renderer: FoundationPagination::Rails)
    - if replies
      #replies.content.active
        = render partial: 'users/activity/replies', locals: { replies: replies }
      = will_paginate(replies, renderer: FoundationPagination::Rails)
    - if favorites
      #favorites.content.active
        = render partial: 'users/activity/favorites', locals: { favorites: favorites }
      = will_paginate(favorites, renderer: FoundationPagination::Rails)

app/views/users/_history.html.slim
.user-history
  ul.tabs data-tab = ''
    li.tab-title.active
      a href='#topics' =t('user.latest_topics')
    li.tab-title
      a href='#replies' =t('user.latest_replies')
    - if current_user.eql?(user)
      li.tab-title
        a href='#favorites' =t('user.my_favorites')
  .tabs-content
    .content.active#topics
      = render partial: 'users/history/topics', locals: { topics: topics }
    .content#replies
      = render partial: 'users/history/replies', locals: { replies: replies }
    - if current_user.eql?(user)
      .content#favorites
        = render partial: 'users/history/favorites', locals: { favorites: favorites }

app/views/users/_profile.html.slim
.profile
  p
    i.fa.fa-fw.fa-chain
    ' &nbsp;&nbsp;
    = link_to profile.blog_link, profile.blog_link
  p
    i.fa.fa-fw.fa-github
    ' &nbsp;&nbsp;
    = link_to profile.github_link, profile.github_link
  p
    i.fa.fa-fw.fa-twitter
    ' &nbsp;&nbsp;
    = link_to profile.twitter_link, profile.twitter_link
  p
    i.fa.fa-fw.fa-users
    ' &nbsp;&nbsp;
    span =profile.company
  p
    i.fa.fa-fw.fa-map-marker
    ' &nbsp;&nbsp;
    span =profile.location

app/views/users/_user.html.slim
.user
  .avatar
    = link_to user_path(user.name) do
      = image_tag user.avatar
  .info
    = link_to user.name, user_path(user.name), class: :username
    br
    - if signed_in? && current_user.eql?(user)
      '
      = link_to " #{t('profile.edit')}", edit_profile_path, class: 'edit fa fa-edit'
    .tips
      = t('user.number_label', number: user.id)
      br
      = sanitize(t('user.joined_time_label', time: timeago_tag(user.created_at)), tags: %w(time))
      - if user.authorization
        br
        = t('user.authorization_label', provider: user.authorization.provider)

app/views/users/index.html.slim
.row.small-collapse.medium-uncollapse
  .columns
    .box
      h5 =t('user_center_title')
      .users
        ul.clearing-thumbs
          - @users.each do |user|
            li
              = link_to user_path(user.name)
                = image_tag user.avatar
              br
              = link_to user.name, user_path(user.name)
      .clearfix
        = will_paginate(@users, renderer: FoundationPagination::Rails)

app/views/users/show.html.slim
- content_for :title
  | #{@user.name} &middot; Streem China
.row.small-collapse.medium-uncollapse
  .large-4.columns
    .box
      = render partial: 'user', locals: { user: @user }
    - if @user.profile
      .box
        = render partial: 'profile', locals: { profile: @user.profile }
  .large-8.columns.no-padding-left-large-up
    .box
      = render partial: 'activity',
               locals: { user: @user,
                         topics: @topics,
                         replies: @replies,
                         favorites: @favorites }